### ISSUE TITLE
Add a filter to show only region-specific earthquakes

### ISSUE THREAD

**Issue by Kvaibhav01** [Kvaibhav01/Quake-Report#8]
There are currently two filters in the app; By magnitude, and By recent. Just add another filter to the settings named "Narrow by region", which should bring up a dialog which asks the user's location to add, by clicking "OK", the `MainActivity` should be refreshed by that region's earthquakes. 

References: 

- [USGS API](https://earthquake.usgs.gov/fdsnws/event/1/)
- [Implementing dilaog with `EditText`](https://stackoverflow.com/questions/18799216/how-to-make-a-edittext-box-in-a-dialog)

**Comment by drcabral** [comment]
Can i try this one?

**Comment by drcabral** [comment]
USGS API does not allow to search directly by a region, it only allows to search using coordinates. Do you want that I use other API that, given a region, returns these coordinates to use with USGS API and fetch earthquakes with these data?

**Comment by drcabral** [comment]
Other option is just use the region to filter with the already fetched data by order and magnitude. In this case, maybe we can increase the total amount of data fetched (from 10 to 100 maybe?). This is an easier way because we don't need to add no one new API to do this. What do you think?

**Comment by drcabral** [comment]
I did a PR considering the second scenario that i mentioned, can you please review it and tell me if it makes sense for you?

**Comment by Kvaibhav01** [comment]
Thank you for the changes @drcabral. I've merged your PR. But it only shows the earthquake list from Japan and if I try to search for any other place it shows nothing!

Like I searched for "USA", "Canada" etc and even cities like "San Francisco", "Delhi". No result! Can you fix that? Feel free to use any other earthquake API but kindly mention about it here in your comment.

**Comment by drcabral** [comment]
As i mentioned @Kvaibhav01, the way that i choose to solve your problem was with pre-fetched data based on magnitud and order. If the 100 first earthquake data based on this parameters has no one from "USA", "Canada" or other cities the search will doesn't fetch any results.

So, if you want to fetch data with these countries directly from the service, i'll need to first use other API to fetch latitud and longitud information, then i can use these information as accepted parameters of USGS to fetch earthquake information only about these regions.

I'll do this improvement as soon as possible (but still today, i think)

**Comment by Kvaibhav01** [comment]
Yes, @drcabral use the other API for that, we really need this feature. And there is no time issue. Do whenever you want to (but not too late).

**Comment by ram2012k** [comment]
@Kvaibhav01  Why it is not showing any data/list 
![screenshot_1539022482](https://user-images.githubusercontent.com/13637219/46626218-429bd380-cb54-11e8-915c-23f31041aa36.png)

**Comment by drcabral** [comment]
As i mentioned before, we are now filtering earthquake info based on magnitud and order. After we fetch based on these parameters, we apply the filter by region. If the last 100 registers does not have any register with the country that you're using, we don't display nothing (because doesn't match with this parameters, in this logic).

But, as i said, i will send another code to fix this logic, fetching content already based in region, and not just applying it after fetch by magnitud and order.

**Comment by drcabral** [comment]
I did some changes to reproduce what we discussed here as best as i can, so, here is the PR that do it.
